### ISSUE TITLE
Log warning: deprecated config paths

### ISSUE THREAD

**Issue by ttusing** [emilyriederer/dbt_dplyr#14]
On run: 
```
06:00:37  [WARNING]: Deprecated functionality
The `source-paths` config has been renamed to `model-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
06:00:37  [WARNING]: Deprecated functionality
The `data-paths` config has been renamed to `seed-paths`. Please update your
`dbt_project.yml` configuration to reflect this change.
```

**Comment by ttusing** [comment]
DBT hub seems to have the `0.3.0` version, it looks like Git goes up to `0.3.1` which does not have this error.

**Comment by ttusing** [comment]
Think a new release is needed on Github for `0.3.1` as reflected on main branch:

https://github.com/emilyriederer/dbtplyr/blob/d15eab017c4abc1d426ef25d9c64ac345479caa6/dbt_project.yml#L6

https://github.com/emilyriederer/dbtplyr/blob/d15eab017c4abc1d426ef25d9c64ac345479caa6/dbt_project.yml#L16-L21

**Comment by emilyriederer** [comment]
Done! Thanks for opening the issue. I've been doing releases mostly for major changes, but hadn't considered how much this might be cluttering people's logs.
