### ISSUE TITLE
Integration test requiring dbt-utils 0.8.4 reduces package compatibility

### ISSUE THREAD

**Issue by ttusing** [emilyriederer/dbt_dplyr#16]
https://github.com/emilyriederer/dbtplyr/blob/main/integration_tests/packages.yml

It would be great to support dbt-utils `0.9.0+`. Is there any reason that the integration tests require specificially `0.8.4`? This is preventing compatibility for using this package and packages requiring `0.9.0+`.

**Comment by emilyriederer** [comment]
Done! Apologies - I had been waiting for a bugfix that was messing with the tests. Looks like all is resolved now.

For my education: does the dependency in the test suite versus the main package impede using the package or trying to further develop it? I wouldn't have expected the test suite version to matter, but that's great to know
